title: The Programming Post
logo: /assets/img/logo.png
description: A blogging plateform about programming
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
author: pgmpost


plugins:
 - jekyll-feed
